-- AlterTable
ALTER TABLE "events" ALTER COLUMN "start_date" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "end_date" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "start_time" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "end_time" SET DATA TYPE VARCHAR(255);
